<?php
require_once './templates/header.phtml';
?>

<div class="container">
    <h1 class="text-center my-4">Listado de Categorías de Habitaciones</h1>
    <ul class="list-group">
        <?php foreach ($categories as $category) : ?>
            <li class="list-group-item">
                <a href="<?= BASE_URL . 'ItemsCategory/' . $category['Tipo'] ?>" class="text-decoration-none">
                    <?= htmlspecialchars($category['Tipo']) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php
require_once './templates/footer.phtml';
?>
