<?php require 'templates/layouts/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='post' action='login'>
    <div class='form-group'>
        <label for='email'>Email</label>
        <input type='email' class='form-control' id='email_usuario' name='email_usuario' required>
    </div>
    <div class='form-group'>
        <label for='password'>Contraseña</label>
        <input type='password' class='form-control' id='contraseña' name='contraseña' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

<?php require 'templates/layouts/footer.phtml' ?>
